from app.schemas import EdgeSignal


def build_edge_signals() -> list[EdgeSignal]:
    return [
        EdgeSignal(
            symbol="NVDA",
            asset_class="stock",
            signal_name="RVOL + Breakout",
            signal_type="rvol_breakout",
            urgency="high",
            time_decay="5-30 min",
            edge_score=86,
            confidence=0.78,
            spread_pass=True,
            liquidity_pass=True,
            regime_pass=True,
            account_fit="needs_smaller_expression",
            recommended_action="Alert only: direct shares may be too large. Watch pullback or defined-risk option spread.",
            alert_status="sent",
            reason="Volume acceleration and breakout structure are aligned, but account sizing needs routing.",
            risk_factors=["fast signal decay", "gap reversal", "account size mismatch"],
        ),
        EdgeSignal(
            symbol="AMD",
            asset_class="option",
            signal_name="Unusual Options Flow",
            signal_type="unusual_options_flow",
            urgency="medium",
            time_decay="15 min-1 day",
            edge_score=81,
            confidence=0.72,
            spread_pass=True,
            liquidity_pass=True,
            regime_pass=True,
            account_fit="feasible_defined_risk",
            recommended_action="Send to options scanner for IV, OI, spread, theta, and underlying confirmation.",
            alert_status="queued",
            reason="Options activity is elevated and underlying trend is supportive.",
            risk_factors=["IV expansion risk", "flow may be hedge not direction"],
        ),
        EdgeSignal(
            symbol="BTC-USD",
            asset_class="crypto",
            signal_name="Volatility Burst",
            signal_type="crypto_volatility_burst",
            urgency="high",
            time_decay="5-60 min",
            edge_score=83,
            confidence=0.70,
            spread_pass=True,
            liquidity_pass=True,
            regime_pass=False,
            account_fit="risk_review",
            recommended_action="Monitor only until volatility regime stabilizes. Consider fractional spot sizing only.",
            alert_status="watch_only",
            reason="BTC volatility and momentum are elevated, but regime risk is not fully supportive.",
            risk_factors=["liquidation cascade", "weekend liquidity", "macro correlation"],
        ),
    ]
