from app.schemas import LiveWatchlistCandidate


def build_live_candidates() -> list[LiveWatchlistCandidate]:
    return [
        LiveWatchlistCandidate(
            symbol="NVDA",
            asset="Stock",
            asset_class="stock",
            horizon="day_trade",
            trigger="RVOL Breakout",
            trigger_type="rvol_breakout",
            priority_score=91,
            trigger_strength=94,
            account_fit="needs_smaller_expression",
            account_fit_label="Needs smaller expression",
            suggested_expression="Defined-risk spread or alert-only watch",
            agent_status="agents_reviewing",
            notify_status="pending_alert",
            notify_label="Pending alert",
            data_quality="prototype",
            reason="Signal requires actionable price plan, spread, liquidity, and account validation before recommendation.",
            risk_factors=["fast decay", "slippage", "account size mismatch"],
        ),
        LiveWatchlistCandidate(
            symbol="AMD",
            asset="Option / Stock",
            asset_class="option",
            horizon="swing",
            trigger="Options Flow",
            trigger_type="unusual_options_flow",
            priority_score=84,
            trigger_strength=86,
            account_fit="feasible_defined_risk",
            account_fit_label="Feasible defined-risk",
            suggested_expression="Debit spread if IV and spread pass",
            agent_status="confirmed",
            notify_status="alert_queued",
            notify_label="Alert queued",
            data_quality="prototype",
            reason="Options flow and underlying momentum align, pending deeper options scanner.",
            risk_factors=["IV risk", "wide spread risk"],
        ),
        LiveWatchlistCandidate(
            symbol="BTC-USD",
            asset="Bitcoin",
            asset_class="crypto",
            horizon="intraday",
            trigger="Volatility Burst",
            trigger_type="crypto_volatility_burst",
            priority_score=82,
            trigger_strength=84,
            account_fit="risk_review",
            account_fit_label="Risk review",
            suggested_expression="Fractional spot or watch-only",
            agent_status="monitoring",
            notify_status="watch_only",
            notify_label="Watch only",
            data_quality="prototype",
            reason="Crypto volatility is elevated; risk agent is monitoring before alert escalation.",
            risk_factors=["high volatility", "liquidation risk"],
        ),
    ]
