from typing import Any

from pydantic import BaseModel, Field


class StrategyConfig(BaseModel):
    strategy_key: str
    display_name: str
    asset_class: str
    timeframe: str
    description: str
    edge_signals: list[str]
    required_agents: list[str]
    optional_agents: list[str]
    required_models: list[str]
    optional_models: list[str]
    required_data_sources: list[str]
    validation_rules: list[str]
    risk_rules: list[str]
    action_rules: list[str]
    default_weights: dict[str, float]
    auto_run_supported: bool
    live_trading_supported: bool = False
    paper_trading_supported: bool = True
    requires_human_approval: bool = True
    metadata: dict[str, Any] = Field(default_factory=dict)


_STRATEGIES: list[StrategyConfig] = [
    StrategyConfig(strategy_key="stock_day_trading", display_name="Stock Day Trading", asset_class="stock", timeframe="day_trade", description="Liquid stock intraday setups using technical, RVOL, spread, volatility, and regime context.", edge_signals=["rvol_spike", "mean_reversion_1_5_min", "short_term_momentum", "breakout"], required_agents=["data_quality", "technical_signal", "volume_order_flow", "volatility", "market_regime", "risk_manager", "portfolio_manager"], optional_agents=["macro_news_impact", "cost_controller"], required_models=["weighted_ranker"], optional_models=["xgboost_ranker", "kalman_trend_filter"], required_data_sources=["market_snapshot", "candles", "volume"], validation_rules=["quality_status must not fail", "spread must be available or warn", "volume required"], risk_rules=["paper only", "max risk per trade required", "human approval required"], action_rules=["watch only until risk review passes", "no live execution"], default_weights={"technical": 0.3, "volume": 0.25, "volatility": 0.15, "regime": 0.15, "risk": 0.15}, auto_run_supported=True),
    StrategyConfig(strategy_key="stock_swing", display_name="Stock Swing", asset_class="stock", timeframe="swing", description="Multi-day stock momentum and breakout setups.", edge_signals=["rvol_spike", "short_term_momentum", "breakout", "regime_shift"], required_agents=["data_quality", "technical_signal", "volume_order_flow", "market_regime", "model_orchestrator", "risk_manager", "portfolio_manager"], optional_agents=["macro_news_impact", "backtesting", "cost_controller"], required_models=["weighted_ranker"], optional_models=["xgboost_ranker", "hmm_regime", "arimax_forecast"], required_data_sources=["market_snapshot", "candles"], validation_rules=["quality_status must not fail", "trend and volume features required"], risk_rules=["paper only", "reward/risk minimum"], action_rules=["route through model orchestrator before recommendation"], default_weights={"technical": 0.35, "volume": 0.2, "regime": 0.2, "model": 0.15, "risk": 0.1}, auto_run_supported=True),
    StrategyConfig(strategy_key="stock_one_month", display_name="Stock One Month", asset_class="stock", timeframe="one_month", description="One-month stock positioning with macro/regime and model confirmation.", edge_signals=["etf_stock_lag_pairs", "breakout", "regime_shift"], required_agents=["data_quality", "technical_signal", "market_regime", "macro_news_impact", "model_orchestrator", "risk_manager"], optional_agents=["backtesting", "portfolio_manager"], required_models=["weighted_ranker"], optional_models=["xgboost_ranker", "arimax_forecast", "hmm_regime"], required_data_sources=["market_snapshot", "candles", "macro_optional"], validation_rules=["macro conflicts must be reviewed when present"], risk_rules=["smaller position sizing", "paper only"], action_rules=["human review before paper trade"], default_weights={"technical": 0.25, "macro": 0.25, "regime": 0.2, "model": 0.2, "risk": 0.1}, auto_run_supported=False),
    StrategyConfig(strategy_key="options_day_trading", display_name="Options Day Trading", asset_class="option", timeframe="day_trade", description="Options intraday review emphasizing options flow, spread/liquidity, IV, and underlying confirmation.", edge_signals=["unusual_calls_puts", "advanced_options_flow", "short_term_momentum"], required_agents=["data_quality", "options_flow", "technical_signal", "volatility", "risk_manager", "portfolio_manager"], optional_agents=["volume_order_flow", "cost_controller"], required_models=["weighted_ranker"], optional_models=["xgboost_ranker"], required_data_sources=["underlying_snapshot", "options_chain", "spread"], validation_rules=["options fields required", "spread must pass"], risk_rules=["defined risk only", "paper only"], action_rules=["no market orders", "human approval required"], default_weights={"options_flow": 0.35, "technical": 0.2, "volatility": 0.2, "liquidity": 0.15, "risk": 0.1}, auto_run_supported=False),
    StrategyConfig(strategy_key="options_swing", display_name="Options Swing", asset_class="option", timeframe="swing", description="Options swing setups using underlying trend, IV, spread, and risk-defined structure.", edge_signals=["unusual_calls_puts", "advanced_options_flow", "breakout"], required_agents=["data_quality", "options_flow", "technical_signal", "volatility", "market_regime", "risk_manager"], optional_agents=["macro_news_impact", "portfolio_manager"], required_models=["weighted_ranker"], optional_models=["xgboost_ranker", "hmm_regime"], required_data_sources=["underlying_snapshot", "options_chain", "candles"], validation_rules=["IV and open interest required"], risk_rules=["defined risk only", "paper only"], action_rules=["human approval required"], default_weights={"options_flow": 0.3, "technical": 0.25, "volatility": 0.2, "regime": 0.15, "risk": 0.1}, auto_run_supported=False),
    StrategyConfig(strategy_key="options_earnings", display_name="Options Earnings", asset_class="option", timeframe="earnings", description="Earnings-focused options review with IV, event, and spread controls.", edge_signals=["advanced_options_flow", "unusual_calls_puts", "retail_sentiment_spike"], required_agents=["data_quality", "options_flow", "volatility", "macro_news_impact", "risk_manager"], optional_agents=["portfolio_manager", "cost_controller"], required_models=["weighted_ranker"], optional_models=["finbert_sentiment"], required_data_sources=["options_chain", "earnings_calendar", "news"], validation_rules=["event date required", "options liquidity required"], risk_rules=["paper only", "defined risk only"], action_rules=["human approval required"], default_weights={"options_flow": 0.3, "volatility": 0.3, "event": 0.2, "risk": 0.2}, auto_run_supported=False),
    StrategyConfig(strategy_key="crypto_intraday", display_name="Crypto Intraday", asset_class="crypto", timeframe="intraday", description="Crypto intraday setups using technical, volume/order-flow proxies, volatility, and macro/regime context.", edge_signals=["order_book_imbalance", "rvol_spike", "short_term_momentum", "mean_reversion_1_5_min"], required_agents=["data_quality", "technical_signal", "volume_order_flow", "volatility", "market_regime", "risk_manager", "portfolio_manager"], optional_agents=["macro_news_impact", "cost_controller"], required_models=["weighted_ranker"], optional_models=["xgboost_ranker", "kalman_trend_filter"], required_data_sources=["market_snapshot", "volume", "candles"], validation_rules=["quality_status must not fail", "volume required"], risk_rules=["paper only", "reduced size in high volatility"], action_rules=["watch only before human approval"], default_weights={"technical": 0.3, "volume": 0.25, "volatility": 0.2, "regime": 0.15, "risk": 0.1}, auto_run_supported=True),
    StrategyConfig(strategy_key="crypto_swing", display_name="Crypto Swing", asset_class="crypto", timeframe="swing", description="Crypto swing setups using momentum, volatility, and macro context.", edge_signals=["rvol_spike", "breakout", "regime_shift", "short_term_momentum"], required_agents=["data_quality", "technical_signal", "volume_order_flow", "volatility", "market_regime", "model_orchestrator", "risk_manager"], optional_agents=["macro_news_impact", "portfolio_manager"], required_models=["weighted_ranker"], optional_models=["xgboost_ranker", "hmm_regime"], required_data_sources=["market_snapshot", "candles"], validation_rules=["quality_status must not fail"], risk_rules=["paper only", "volatility sizing"], action_rules=["human approval required"], default_weights={"technical": 0.3, "volume": 0.2, "volatility": 0.2, "regime": 0.2, "risk": 0.1}, auto_run_supported=True),
    StrategyConfig(strategy_key="crypto_cycle", display_name="Crypto Cycle", asset_class="crypto", timeframe="one_month", description="Cycle-aware crypto positioning using regime, macro, trend, and volatility features.", edge_signals=["regime_shift", "breakout", "retail_sentiment_spike"], required_agents=["data_quality", "market_regime", "technical_signal", "macro_news_impact", "model_orchestrator", "risk_manager"], optional_agents=["backtesting", "trade_journal"], required_models=["weighted_ranker"], optional_models=["hmm_regime", "arimax_forecast", "finbert_sentiment"], required_data_sources=["market_snapshot", "macro_optional", "sentiment_optional"], validation_rules=["regime context required"], risk_rules=["paper only", "human approval required"], action_rules=["no live execution"], default_weights={"regime": 0.3, "macro": 0.25, "technical": 0.2, "model": 0.15, "risk": 0.1}, auto_run_supported=False),
]


def list_strategies() -> list[StrategyConfig]:
    return _STRATEGIES


def get_strategy(strategy_key: str) -> StrategyConfig | None:
    return next((strategy for strategy in _STRATEGIES if strategy.strategy_key == strategy_key), None)
