from __future__ import annotations


def get_intraday_playbooks() -> list[dict]:
    return [
        {
            "strategy_key": "relative_volume_momentum_breakout_v1",
            "setup_type": "momentum_breakout",
            "description": "Relative volume momentum breakout with VWAP confirmation.",
            "allowed_sessions": ["pre_market", "regular", "post_market"],
            "min_price": 2,
            "max_price": 75,
            "max_spread_bps": 20,
            "min_relative_volume": 2.0,
            "min_liquidity_score": 50,
            "min_trend_score": 55,
            "requires_price_above_vwap": True,
            "target_r": 2.0,
            "status": "active",
        },
        {
            "strategy_key": "vwap_pullback_continuation_v1",
            "setup_type": "vwap_pullback",
            "description": "VWAP pullback continuation during regular session.",
            "allowed_sessions": ["regular"],
            "min_price": 2,
            "max_price": 75,
            "max_spread_bps": 15,
            "min_relative_volume": 1.5,
            "min_liquidity_score": 55,
            "min_trend_score": 60,
            "requires_price_above_vwap": True,
            "target_r": 1.5,
            "status": "active",
        },
        {
            "strategy_key": "filtered_opening_range_breakout_v1",
            "setup_type": "opening_range_breakout",
            "description": "Opening range breakout filtered by liquidity and trend.",
            "allowed_sessions": ["regular"],
            "min_price": 2,
            "max_price": 75,
            "max_spread_bps": 20,
            "min_relative_volume": 1.8,
            "min_liquidity_score": 50,
            "min_trend_score": 50,
            "requires_price_above_vwap": False,
            "target_r": 2.0,
            "status": "active",
        },
        {
            "strategy_key": "liquidity_reclaim_v1",
            "setup_type": "liquidity_reclaim",
            "description": "Liquidity reclaim setup with controlled spread.",
            "allowed_sessions": ["regular", "post_market"],
            "min_price": 2,
            "max_price": 75,
            "max_spread_bps": 20,
            "min_relative_volume": 1.5,
            "min_liquidity_score": 60,
            "min_trend_score": 40,
            "requires_price_above_vwap": False,
            "target_r": 1.5,
            "status": "active",
        },
        {
            "strategy_key": "no_trade_v1",
            "setup_type": "no_trade",
            "description": "No trade when no setup qualifies.",
            "allowed_sessions": [],
            "status": "active",
        },
    ]
